config/routes.rb
Rails.application.routes.draw do
  resources :electros

  resources :news

  resources :projects

  resources :products

  resources :lamps

  resources :brands

  get 'edit_brands' => 'brands#edit_page'
  get 'contact' => 'lamps#contact', as: :contact
  get 'about' => 'lamps#about', as: :about
  get 'sort' => 'lamps#sort', as: :sort
  get 'admin' => 'lamps#lamps_admin', as: :lamps_admin

  root 'lamps#index'

end

app/models/electro.rb
class Electro < ActiveRecord::Base
end

app/controllers/electros_controller.rb
class ElectrosController < ApplicationController
  before_action :set_electro, only: [:show, :edit, :update, :destroy]
  before_filter :authentication_check, except: :index 
  layout "admin", except: :index
  # GET /electros
  # GET /electros.json
  def index
    @electros = Electro.all
  end

  # GET /electros/1
  # GET /electros/1.json
  def show
  end

  # GET /electros/new
  def new
    @electro = Electro.new
  end

  # GET /electros/1/edit
  def edit
  end

  # POST /electros
  # POST /electros.json
  def create
    @electro = Electro.new(electro_params)
    unless params[:electro][:img].nil?
      @electro.img = params[:electro][:img].original_filename
      upload_image params[:electro][:img]
    end
    respond_to do |format|
      if @electro.save
        format.html { redirect_to @electro, notice: 'Electro was successfully created.' }
        format.json { render :show, status: :created, location: @electro }
      else
        format.html { render :new }
        format.json { render json: @electro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /electros/1
  # PATCH/PUT /electros/1.json
  def update
    respond_to do |format|
      if @electro.update(electro_params)
        format.html { redirect_to @electro, notice: 'Electro was successfully updated.' }
        format.json { render :show, status: :ok, location: @electro }
      else
        format.html { render :edit }
        format.json { render json: @electro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electros/1
  # DELETE /electros/1.json
  def destroy
    @electro.destroy
    respond_to do |format|
      format.html { redirect_to electros_url, notice: 'Electro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   #Uplaod method
    def upload_image file_put
      File.open(Rails.root.join('public', 'uploads', file_put.original_filename), 'wb') do |file|
        file.write(file_put.read)
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_electro
      @electro = Electro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def electro_params
      params.require(:electro).permit(:img, :name, :about)
    end
end

app/helpers/electros_helper.rb
module ElectrosHelper
end

app/views/electros/_form.html.erb
<div class="lightcontainer">
<%= form_for(@electro) do |f| %>
  <% if @electro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@electro.errors.count, "error") %> prohibited this electro from being saved:</h2>

      <ul>
      <% @electro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Изображение<br>
    <%= f.file_field :img, class: "form-control" %>
  </div>
  <div class="field">
    Название<br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    Описание<br>
    <%= f.text_area :about, class: "form-control" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit 'Создать', class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/electros/edit.html.erb
<h1>Editing electro</h1>

<%= render 'form' %>

<%= link_to 'Show', @electro %> |
<%= link_to 'Back', electros_path %>

app/views/electros/index.html.erb
 <!-- PAGE TITLE -->
            <h1 class="subtitle btitle">ЭЛЕКТРОУСТАНОВКА</h1>
            <!-- ARTICLE -->
            <% unless session[:is_admin].nil? %>
              <%= link_to 'Добавить', new_electro_path %>
            <% end %>
            <% @electros.each do | electro | %>
                <article class="blogcontainer">
                    <div class="blogimage">
                            <img class="first-img" src="/uploads/<%= electro.img %>" alt="" />
                        <div class="mask"></div>
                    </div>
                    <div class="blogexcerpt">
                        <p class="blogdate"><%= electro.name %></p>
                        <%= electro.about %>
                        
                        <% unless session[:is_admin].nil? %>
                        <br/>
                            <%= link_to 'Edit', edit_electro_path(electro), class: "button" %>
                            <%= link_to 'Destroy', electro, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
                        <% end %>
                    </div>
                </article>
            <% end %>

app/views/electros/new.html.erb
<h1>Добавить електроустановку</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Назад', electros_path, class: "btn btn-default" %>

app/views/electros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Img:</strong>
  <%= @electro.img %>
</p>

<p>
  <strong>Name:</strong>
  <%= @electro.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @electro.about %>
</p>

<%= link_to 'Edit', edit_electro_path(@electro) %> |
<%= link_to 'Back', electros_path %>