config/routes.rb
Rails.application.routes.draw do
  resources :electros

  resources :news

  resources :projects

  resources :products

  resources :lamps

  resources :brands

  get 'edit_brands' => 'brands#edit_page'
  get 'contact' => 'lamps#contact', as: :contact
  get 'about' => 'lamps#about', as: :about
  get 'sort' => 'lamps#sort', as: :sort
  get 'admin' => 'lamps#lamps_admin', as: :lamps_admin

  root 'lamps#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authentication_check, except: :index 
  layout "admin", except: :index
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    unless params[:project][:img].nil?
      @project.img = params[:project][:img].original_filename
      upload_image params[:project][:img]
    end
    unless params[:project][:img2].nil?
      @project.img2 = params[:project][:img2].original_filename
      upload_image params[:project][:img2]      
    end
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #Uplaod method
    def upload_image file_put
      File.open(Rails.root.join('public', 'uploads', file_put.original_filename), 'wb') do |file|
        file.write(file_put.read)
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:img, :img2, :date, :about, :name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Изображение<br>
    <%= f.file_field :img, class: "form-control" %>
  </div>
  <div class="field">
    Изображение<br>
    <%= f.file_field :img2, class: "form-control" %>
  </div>
  <div class="field">
    Дата<br>
    <%= f.text_field :date, class: "form-control" %>
  </div>
  <div class="field">
    Название<br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    Описание<br>
    <%= f.text_area :about, class: "form-control" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit 'Создать', class: "btn btn-success" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="lightcontainer">
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project, class: "button" %> 
<%= link_to 'Back', projects_path, class: "button"  %>

</div>

app/views/projects/index.html.erb
<style>
    .blogimage img.last-img {
        margin-top: -256px;
        display: none;
    }    
</style>
            <!-- PAGE TITLE -->
            <h1 class="subtitle btitle">Проекты</h1>
            <!-- ARTICLE -->
            <% @projects.each do | project | %>
                <article class="blogcontainer">
                    <div class="blogimage">
                            <a class="clb-photo" href="/uploads/<%= project.img %>" data-rel="latest-<%= project.id %>">
                                <img class="first-img" src="/uploads/<%= project.img %>" alt="" />
                            </a>
                            <% unless project.img2.nil? %>
                            <a class="clb-photo" href="/uploads/<%= project.img2 %>" data-rel="latest-<%= project.id %>">
                              <img class="last-img" src="/uploads/<%= project.img2 %>" alt="" /> 
                            </a>
                            <% end %> 
                        <div class="mask"></div>
                    </div>
                    <div class="blogexcerpt">
                        <!--p class="blogdate">Дата: <%= project.date %></p-->
                        <p class="blogdate"><%= project.name %></p>
                        <%= project.about %>
                        
                        <% unless session[:is_admin].nil? %>
                        <br/>
                            <%= link_to 'Edit', edit_project_path(project), class: "button" %>
                            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
                        <% end %>
                    </div>
                </article>
            <% end %>
            <!-- ARTICLE -->
            <!-- PAGER -->
            <!--div class="blogpager">
                <div class="previous">
                    <a href="#" class="button next-prev">&#8249; Older Posts</a>
                </div>
                <div class="next">
                    <a href="#" class="button next-prev">Newer Posts &#8250;</a>
                </div>
            </div-->
            

app/views/projects/new.html.erb
<h1>Новый проект</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Назад', projects_path, class: "btn btn-default" %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Img:</strong>
  <%= @project.img %>
</p>

<p>
  <strong>Date:</strong>
  <%= @project.date %>
</p>

<p>
  <strong>About:</strong>
  <%= @project.about %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>