config/routes.rb
Rails.application.routes.draw do
  resources :electros

  resources :news

  resources :projects

  resources :products

  resources :lamps

  resources :brands

  get 'edit_brands' => 'brands#edit_page'
  get 'contact' => 'lamps#contact', as: :contact
  get 'about' => 'lamps#about', as: :about
  get 'sort' => 'lamps#sort', as: :sort
  get 'admin' => 'lamps#lamps_admin', as: :lamps_admin

  root 'lamps#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authentication_check, except: :index 
  layout "admin", except: :index
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.img = params[:product][:img].original_filename
    upload_image params[:product][:img]
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #Uplaod method
    def upload_image file_put
      File.open(Rails.root.join('public', 'uploads', file_put.original_filename), 'wb') do |file|
        file.write(file_put.read)
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:img, :price, :about, :size, :amount, :article, :brand, :metal_color, :glass_color, :availability, :new_product)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Изображение<br>
    <%= f.file_field :img, class: "form-control" %>
  </div>
  <div class="field">
    Цена<br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="field">
    Описание<br>
    <%= f.text_area :about, class: "form-control" %>
  </div>
  <div class="field">
    Размеры<br>
    <%= f.number_field :size, class: "form-control" %>
  </div>
  <div class="field">
    Количество<br>
    <%= f.number_field :amount, class: "form-control" %>
  </div>
  <div class="field">
    Артикул<br>
    <%= f.number_field :article, class: "form-control" %>
  </div>
  <div class="field">
   Бренд<br>
    <%= f.text_field :brand, class: "form-control" %>
  </div>
  <div class="field">
    Цвет метала<br>
    <%= f.text_field :metal_color,class: "form-control" %>
  </div>
  <div class="field">
    Цвет стекла<br>
    <%= f.text_field :glass_color, class: "form-control" %>
  </div>
  <div class="field">
    В наличии<br>
    <%= f.check_box :availability, class: "form-control" %>
  </div>
  <div class="field">
    Новый продукт<br>
    <%= f.check_box :new_product, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Создать', class: "btn btn-success" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="lightcontainer">
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product, class: "button"  %> 
<%= link_to 'Back', products_path, class: "button"  %>
</div>

app/views/products/index.html.erb
            <!-- PAGE TITLE -->
            <h1 class="subtitle btitle">Каталог</h1>
            <!-- ARTICLE -->
            <% @products.each do | product | %>
                <article class="blogcontainer">
                    <div class="blogimage">
                        <img src="/uploads/<%= product.img %>" alt="" />
                        <div class="mask"></div>
                    </div>
                    <div class="blogexcerpt">
                            <h5><%= product.brand %></h5>
                        <p class="blogdate">Артикул: <%= product.article %></p>
                        <!--p class="blogdate">Цена: <%= product.price %></p-->
                        <%= product.about %>
                        
                        <% unless session[:is_admin].nil? %>
                        <br/>
                            <%= link_to 'Edit', edit_product_path(product), class: "button" %>
                            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
                        <% end %>
                    </div>
                </article>
            <% end %>
            <!-- ARTICLE -->
            <!-- PAGER -->
            <!--div class="blogpager">
                <div class="previous">
                    <a href="#" class="button next-prev">&#8249; Older Posts</a>
                </div>
                <div class="next">
                    <a href="#" class="button next-prev">Newer Posts &#8250;</a>
                </div>
            </div-->

app/views/products/new.html.erb
	<h1>Новый продукт</h1>

	<%= render 'form' %>
	<br/>
	<%= link_to 'Назад', products_path, class: "btn btn-default" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Img:</strong>
  <%= @product.img %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>About:</strong>
  <%= @product.about %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @product.amount %>
</p>

<p>
  <strong>Article:</strong>
  <%= @product.article %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Metal color:</strong>
  <%= @product.metal_color %>
</p>

<p>
  <strong>Glass color:</strong>
  <%= @product.glass_color %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>