config/routes.rb
Rails.application.routes.draw do
  resources :electros

  resources :news

  resources :projects

  resources :products

  resources :lamps

  resources :brands

  get 'edit_brands' => 'brands#edit_page'
  get 'contact' => 'lamps#contact', as: :contact
  get 'about' => 'lamps#about', as: :about
  get 'sort' => 'lamps#sort', as: :sort
  get 'admin' => 'lamps#lamps_admin', as: :lamps_admin

  root 'lamps#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Admin panel</title>
    <%= stylesheet_link_tag    'admin', media: 'all' %>
    <%= javascript_include_tag 'admin'%>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
            <li><a href="/brands/new">Добавить бренд</a></li>
            <li><a href="/products/new">Добавить продукт</a></li>
            <li><a href="/news/new">Добавить новость</a></li>
            <li><a href="/projects/new">Добавить проект</a></li>
            <li><a href="/electros/new">Добавить електорустановку</a></li>
        </ul>
        <h3 class="text-muted"><a href="/admin/">Админ панель</a></h3>
      </div>

      <%= yield %>

    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <title>ASSO&LUCE - Световой салон</title>
		  <%= stylesheet_link_tag    'application', media: 'all' %>
		  <%= javascript_include_tag 'application'%>
		  <%= csrf_meta_tags %>
    </head>
    
    <body>
        <!-- BG FILTERS -->
        <div id="left-bg"></div>
        <div id="right-bg"></div>
        <!-- MAIN MENU -->
        <div class="fix-nav">
            <div class="nav-container">
                <!-- LOGO -->
                <div class="logo">
                    <a href="/"><img src="/images/logo.png" alt="" /></a>
                </div>
                <!-- MOBILE MENU ICON -->
                <a class="toggleMenu" href="index.html#">Menu</a>
                <!-- MENU -->
                <nav>
                    <ul class="nav">
                        <li>
                            <%= link_to "Бренды", brands_path %>
                        </li>
                        <li>
                            <%= link_to "Проекты", projects_path %>
                        </li>
                        <li>
                            <%= link_to "Продукты", products_path %>
                        </li>
                        <li>
                            <%= link_to "Новости", news_index_path %>
                        </li>
                        <li>
                            <%= link_to "Контакты", contact_path %>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
       <div class="maincontainer">
        <%= yield %>

        <!-- FOOTER -->
            <footer>
                <div id="footer-widgets">
                    <div class="footer-widget first-clmn">
                        <h5>Последние поступления</h5>
                        <ul>
                            <li>
                                <a href="">Osram</a>
                            </li>
                            <li>
                                <a href="">Sylvania</a>
                            </li>
                            <li>
                                <a href="">Philips</a>
                            </li>
                            <li>
                                <a href="">Nakai</a>
                            </li>
                            <li>
                                <a href="">Hitachi</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-widget second-clmn">
                        <h5>Розетки и выключатели</h5>
                        <ul>
                            <li>
                                <a href="">Gira</a>
                            </li>
                            <li>
                                <a href="">Legrand</a>
                            </li>
                            <li>
                                <a href="">Btcino</a>
                            </li>
                            <li>
                                <a href="">Fontini</a>
                            </li>
                            <li>
                                <a href="">ABB</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-widget third-clmn">
                        <!--h5>Витрина</h5>
                        <ul id="cbox" class="flickr-box"></ul-->
                    </div>
                </div>
                <div class="clear"></div>
                <div class="credits">© 2014 Asso&Luce.</div>
                <!-- SOCIAL ICONS -->
                <!--ul class="social-icons">
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/facebook.png" alt="Facebook" />
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/twitter.png" alt="Twitter" />
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/flickr.png" alt="Flickr" />
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/linkedin.png" alt="Linked in" />
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/google+.png" alt="Google+" />
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/vimeo.png" alt="Vimeo" />
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <img class="social-icon" src="images/social-icons/youtube.png" alt="YouTube" />
                        </a>
                    </li>
                </ul-->
            </footer>
            <!-- BACK TO TOP BUTTON -->
            <a href="#" class="back-to-top"></a>
        </div>
        <!-- ZEUS SLIDER -->
        <script type="text/javascript">
            $(window).load(function() {

                $("#slide1").zeusslider({
                    autoplay: true,
                    duration: 5000,
                    onslidechange: function() {
                        $("#slide1").find('.zeus-text-right').addClass('bounceInDown');
                        $("#slide1").find('.zeus-text-left').addClass('bounceInUp');
                        setTimeout(function() {
                            $("#slide1").find('.zeus-text-right').removeClass('bounceInDown');
                            $("#slide1").find('.zeus-text-left').removeClass('bounceInUp');
                        }, 1000);
                    }
                });
            });
        </script>
        <!-- BG IMAGE -->
        <script type="text/javascript">
            $(window).load(function() {
                "use strict";
                $('body').backstretch("images/photos/bg.jpg");
            });
        </script>
        <script type="text/javascript" src="js/custom.js"></script>
    </body>

</html>